### PR TITLE
[RHOSINFRA-129] Fixes all parameters are optionals in help screen

### PR DESCRIPTION
**Pull request by aopincar**
Help screen displays all parameters as optionals.
This fixes skip the preprocess arguments stage if '-h'/'--help' is
given.

Resolves RHOSINFRA-129

### CODE REVIEW

**Comment by aopincar** [comment]
retest openstack

**Comment by aopincar** [comment]
retest virsh

**Comment by aopincar** [comment]
retest openstack

**Comment by obaranov** [comment]
The default value and the allowed yaml files are not printed into the help. Is that expected and acceptable untill the clg update and rework? 

Here what was before:
```
Hypervisor:
  --host-address HOST-ADDRESS
                        Address/FQDN of the BM hypervisor
  --host-user HOST-USER
                        User to SSH to the host with
                        Default value: root
  --host-key HOST-KEY   User's SSH key
                        Default value: ~/.ssh/id_rsa

image:
  --image IMAGE         The image to use for nodes provisioning. Check the 'sample.yml.example' for example.
                        Allowed values: { rhel-7.2.yml, sample.yml.example }
```
And now: 

```
Hypervisor:
  --host-address HOST-ADDRESS
                        Address/FQDN of the BM hypervisor
  --host-user HOST-USER
                        User to SSH to the host with
  --host-key HOST-KEY   User's SSH key

image:
  --image IMAGE         The image to use for nodes provisioning. Check the 'sample.yml.example' for example.

```

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
Openstack gate fails due to bad shade version (1.8.0) please pull latest master and resubmit

**Comment by aopincar** [comment]
```
$ ir-provisioner virsh --help
usage: ir-provisioner virsh [-h] --host-address HOST-ADDRESS
                            [--host-user HOST-USER] [--host-key HOST-KEY]
                            --image IMAGE
                            [--topology-network TOPOLOGY-NETWORK]
                            [--topology-nodes TOPOLOGY-NODES] [--dry-run]
                            [--cleanup] [-i INPUT] [-o OUTPUT] [-e EXTRA-VARS]
                            [--from-file FROM-FILE]
                            [--generate-conf-file GENERATE-CONF-FILE]

optional arguments:
  -h, --help            show this help message and exit

Hypervisor:
  --host-address HOST-ADDRESS
                        Address/FQDN of the BM hypervisor
  --host-user HOST-USER
                        User to SSH to the host with
                        Default value: root
  --host-key HOST-KEY   User's SSH key
                        Default value: ~/.ssh/id_rsa

image:
  --image IMAGE         The image to use for nodes provisioning. Check the 'sample.yml.example' for example.
                        Allowed values: { sample.yml.example }

topology:
  --topology-network TOPOLOGY-NETWORK
                        Network
                        Default value: default.yml
                        Allowed values: { default.yml }
  --topology-nodes TOPOLOGY-NODES
                        Provision topology.
                        Default value: undercloud:1,controller:1,compute:1

common:
  --dry-run             Only generate settings, skip the playbook execution stage
  --cleanup             Clean given system instead of provisioning a new one
  -i INPUT, --input INPUT
                        Input settings file to be loaded before the merging of user args
  -o OUTPUT, --output OUTPUT
                        File to dump the generated settings into (default: stdout)
  -e EXTRA-VARS, --extra-vars EXTRA-VARS
                        Extra variables to be merged last
  --from-file FROM-FILE
                        the ini file with the list of arguments
  --generate-conf-file GENERATE-CONF-FILE
                        generate configuration file (ini) containing default values and exits. This file is than can be used with the from-file argument
```

**Pull request merged**
