### PR TITLE
Change overcloud VMs name to start at index 0

### PR DESCRIPTION
**Pull request by mcornea**
This change enables the creation of overcloud VMs by using an index starting at 0 in the form of <role>-<index>

It addresses issue #229

### CODE REVIEW

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by tkammer** [comment]
Thanks for the help!
We're currently switching our bash to ansible tasks, would you mind rebasing this on the newly supported playbook?

**Comment by yfried-redhat** [comment]
In #244 the the way we create and name nodes is being refactored. Could you please review and make sure it suits your request?

**Comment by yfried-redhat** [comment]
This is partially addressed by #244. Closing.

**Pull request closed without merging**
