### PR TITLE
py3 compatibility fixes

### PR DESCRIPTION
**Pull request by ssbarnea**
These changes are adding support for Python 3 while keeping the code backwards compatible.

Note: the tests are not passing yet on py3 because Ansible does not work on py3 yet. Still, this is solving infrared specific py3 issues.

### CODE REVIEW

**Comment by yfried-redhat** [comment]
Hi @ssbarnea,
Thank you for this patch. Could you please submit it via our Gerrit project (`git review`), as we no longer use GitHub PRs

Regards
Yair

**Comment by tkammer** [comment]
@ssbarnea 
Hey! Just to give some more details, you can run this command to clone it from gerrit and apply the hook to run git review:
git clone https://review.gerrithub.io/rhosqeauto/InfraRed && (cd InfraRed && curl -kLo `git rev-parse --git-dir`/hooks/commit-msg https://review.gerrithub.io/tools/hooks/commit-msg; chmod +x `git rev-parse --git-dir`/hooks/commit-msg)
We're here for support if you need anything.

**Comment by ssbarnea** [comment]
When I try to do `git review` on the repository I get 
```
fatal: Upload denied for project 'rhosqeauto/InfraRed'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

Please note that this happened after I made a local commit in the master branch. Before doing this I was getting this:
```
>$git review
No changes between HEAD and gerrit/master. Submitting for review would
be pointless.
```

**Comment by ssbarnea** [comment]
I created a review at https://review.gerrithub.io/#/c/299147/ and it did build successfully. If you or anyone else would review it it would be great. Thanks.

**Pull request closed without merging**
