### PR TITLE
RHOSINFRA-1 Adds rhos-relesae module

### PR DESCRIPTION
**Pull request by yfried-redhat**

### CODE REVIEW

**Comment by yfried-redhat** [comment]
RHOSINFRA-1 check JIRA

**Comment by tkammer** [comment]
Lets talk about this, I see some issues here

**Comment by gamado** [comment]
Can one of the admins verify this patch?

**Comment by gamado** [comment]
test this please

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by gamado** [comment]
retest

**Pull request closed without merging**
