### PR TITLE
Modify README.rst

### PR DESCRIPTION
**Pull request by bregman-arie**
Users may wonder what exactly should be in infrared.cfg
and not aware that there is an sample file in repo root.

### CODE REVIEW

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by yfried-redhat** [comment]
@

**Comment by yfried-redhat** [comment]
@bregman-arie This PR is now mixed with the openstack code. please submit a new one

**Pull request closed without merging**
