### PR TITLE
Add settings for new provisioner - openstack

### PR DESCRIPTION
**Pull request by bregman-arie**
Added settings for new provisioner 'openstack'.

The provisioner will allow to lunch instances on existing openstack
clouds, using Ansible cloud modules.

### CODE REVIEW

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by yfried-redhat** [comment]
@bregman-arie please add playbooks so we can test this

**Comment by tkammer** [comment]
This will be pushed together with the playbooks

**Pull request closed without merging**
