### PR TITLE
Add 'ipaddress' to requirements.txt

### PR DESCRIPTION
**Pull request by bregman-arie**
Needed for os_floating_ip module.

### CODE REVIEW

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by rhosqeauto** [comment]
Can one of the admins verify this patch?

**Comment by yfried-redhat** [comment]
ok to test

**Comment by bregman-arie** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack
￼

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack
retest virsh

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Comment by yfried-redhat** [comment]
retest openstack

**Pull request merged**
